"""One-page resume rendering: PDF + Word from the SAME markdown, same layout.

The owner's rules for every tailored resume: ONE page, delivered as a PDF and
a matching Word .docx, named ``First_Last_Resume``, with no trace of the
generator in the file metadata.

How the pieces fit:

* ``parse_md`` reads the tailored markdown with exactly the line mapping
  ``tailor._md_to_docx`` uses ("# " = name / Heading 1, "## " = section /
  Heading 2, "### " = subhead / Heading 3, "- "/"* " = List Bullet, anything
  else = Normal; ``**bold**`` / ``*italic*`` become runs), so the PDF and the
  DOCX say the same thing in the same order.
* ``TIERS`` are layouts from the current Word look (T0: 11pt Calibri, 0.75in,
  Word's 1.15 line spacing) down to T3 (9.5pt, 0.5in, single spacing). Nothing
  goes below 9.5pt body or 0.5in margins - readability and ATS parsing.
* The PDF is laid out by THIS module (greedy word wrap over the glyph advance
  widths of the bundled Carlito font, which is metric-compatible with Calibri,
  then one ``text()`` per run per line), so "will it fit on one page?" is
  plain arithmetic: ``fit_one_page`` can try every tier and every trim
  without producing a PDF, and the single PDF it does produce paginates by the
  same function that answered. ``page_count`` re-checks the bytes with pypdf.
* A layout counts as fitting only with about one body line to spare: Word
  breaks lines with its own engine, and a resume that fills the PDF page to
  the last point can spill onto a second page in Word.
* When even T3 is two pages, ``fit_one_page`` REMOVES whole bullets - least
  relevant to the job description first, then the older role, then the
  longer bullet - and never adds or rewrites a word: every line was already
  fact-checked by the tailoring pipeline. Header, headings, role lines
  (bulleted ones included), summary, skills and education are never touched,
  and every run of bullets under a role line keeps at least one.
* ``render_pdf`` / ``write_docx`` stamp the candidate as author, leave
  creator/producer empty and scrub the generator defaults (fpdf2's subset
  tag, python-docx's "generated by python-docx" core properties, its static
  app.xml, template thumbnail, bibliography part and the revision ids every
  python-docx file shares).
* ``FitResult.undrawable`` lists characters the bundled font has no glyph
  for (a name in CJK script): the PDF would print "?" for them, so the
  caller ships the Word file alone.

Everything here is CPU-only and in-process: no network, no browser, no LLM.
"""
from __future__ import annotations

import hashlib
import io
import logging
import os
import re
import tempfile
import threading
import unicodedata
import zipfile
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Union
from xml.sax.saxutils import escape as _xml_escape

log = logging.getLogger(__name__)
# fontTools logs every subset table it writes at INFO: dozens of lines per PDF.
logging.getLogger("fontTools").setLevel(logging.WARNING)

FONT_DIR = Path(__file__).resolve().parent / "fonts"
_FONT_FAMILY = "Carlito"
_FONT_FILES = {
    "": "Carlito-Regular.ttf",
    "B": "Carlito-Bold.ttf",
    "I": "Carlito-Italic.ttf",
}

# US Letter, in points.
PAGE_W_PT = 612.0
PAGE_H_PT = 792.0

# Word lays out a "single" line of Calibri at (winAscent + winDescent) / upem
# of the font size = 2500 / 2048. Carlito has identical vertical metrics.
_WIN_ASCENT = 1950 / 2048
_WIN_DESCENT = 550 / 2048
LINE_FACTOR = _WIN_ASCENT + _WIN_DESCENT  # 1.2207...

_DARK = (0x1F, 0x1F, 0x1F)   # headings, as _set_ats_safe_styles colours them
_BODY = (0, 0, 0)            # Word's "auto" text colour
_RULE = (0x80, 0x80, 0x80)   # thin rule under section headings
_RULE_GAP_PT = 1.0           # Word pBdr w:space="1"
_RULE_W_PT = 0.5             # Word pBdr w:sz="4" (eighths of a point)
_RULE_PAD_PT = _RULE_GAP_PT + _RULE_W_PT
_BULLET = "\u2022"
_EPS = 1e-6

# Markers that must never appear in a delivered file's metadata.
GENERATOR_MARKERS = (
    "fpdf", "pyfpdf", "pypdf", "python-docx", "claude", "anthropic", "openai",
    "gpt", "ai-generated", "spotapply", "hirepath", "generated by",
    "microsoft macintosh word", "mpdfaa",
)


# ── Tiers ────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class Tier:
    """One layout density. Sizes in points, margins/indent in inches.

    ``line_spacing`` is Word's "multiple" line spacing (1.15 is what the
    python-docx template's docDefaults give every paragraph today).
    """
    name: str
    body_pt: float
    h1_pt: float
    h2_pt: float
    h3_pt: float
    margin_in: float
    line_spacing: float
    para_after_pt: float
    bullet_after_pt: float
    h1_after_pt: float
    h2_before_pt: float
    h2_after_pt: float
    h3_before_pt: float
    h3_after_pt: float
    bullet_indent_in: float = 0.25

    @property
    def margin_pt(self) -> float:
        return self.margin_in * 72.0

    @property
    def bullet_indent_pt(self) -> float:
        return self.bullet_indent_in * 72.0


MIN_BODY_PT = 9.5
MIN_MARGIN_IN = 0.5

TIERS: tuple[Tier, ...] = (
    # T0 = the current Word export (_set_ats_safe_styles): 11/14/12/11pt,
    # 0.75in margins, Normal after 2pt, bullets after 1pt, H1 after 4pt,
    # H2 6/2pt, H3 4/1pt, 1.15 line spacing from the template's docDefaults.
    Tier("T0", 11.0, 14.0, 12.0, 11.0, 0.75, 1.15, 2.0, 1.0, 4.0, 6.0, 2.0, 4.0, 1.0),
    Tier("T1", 10.5, 13.5, 11.5, 10.5, 0.6, 1.1, 2.0, 1.0, 3.0, 5.0, 2.0, 3.0, 1.0),
    Tier("T2", 10.0, 13.0, 11.0, 10.0, 0.5, 1.05, 1.5, 0.5, 2.0, 4.0, 1.5, 2.0, 0.5),
    Tier("T3", 9.5, 12.5, 10.5, 9.5, 0.5, 1.0, 1.0, 0.0, 2.0, 3.0, 1.0, 2.0, 0.0),
)


def _tier(t: Union[Tier, int]) -> Tier:
    if isinstance(t, Tier):
        return t
    return TIERS[int(t)]


# ── Markdown -> blocks (the _md_to_docx mapping) ─────────────────────────────

@dataclass(frozen=True)
class Run:
    text: str
    bold: bool = False
    italic: bool = False


@dataclass(frozen=True)
class Block:
    """One rendered paragraph.

    kind: ``name`` (# , Heading 1), ``header`` (Normal line before the first
    section), ``section`` (## , Heading 2), ``subhead`` (### , Heading 3),
    ``bullet`` (- / * , List Bullet) or ``para`` (Normal).
    ``line_no`` indexes ``md.splitlines()`` so a trim removes exactly that line.
    """
    kind: str
    runs: tuple[Run, ...]
    line_no: int
    raw: str

    @property
    def text(self) -> str:
        return "".join(r.text for r in self.runs)


_INLINE_RE = re.compile(r"(\*\*[^*\n]+\*\*|\*[^*\n]+\*)")
_HR_RE = re.compile(r"^[-*_ ]+$")


def _runs(text: str) -> tuple[Run, ...]:
    """``tailor._add_formatted_run``'s split, as data."""
    out: list[Run] = []
    for part in _INLINE_RE.split(text):
        if not part:
            continue
        if part.startswith("**") and part.endswith("**") and len(part) > 4:
            out.append(Run(part[2:-2], bold=True))
        elif part.startswith("*") and part.endswith("*") and len(part) > 2:
            out.append(Run(part[1:-1], italic=True))
        else:
            out.append(Run(part))
    return tuple(out)


def parse_md(md: str) -> list[Block]:
    """Markdown resume -> blocks, line for line as ``_md_to_docx`` maps it.

    Skipped exactly as there: blank lines, code fences, horizontal rules.
    Lines before the first "## " that are not headings or bullets are
    ``header`` (contact line, headline); after it they are ``para``.
    """
    blocks: list[Block] = []
    seen_section = False
    for i, line in enumerate((md or "").splitlines()):
        s = line.strip()
        if not s or s.startswith("```"):
            continue
        if _HR_RE.match(s) and len(s) >= 3:
            continue
        if s.startswith("# "):
            kind, body = "name", s[2:].strip()
        elif s.startswith("## "):
            kind, body = "section", s[3:].strip()
            seen_section = True
        elif s.startswith("### "):
            kind, body = "subhead", s[4:].strip()
        elif s.startswith("- ") or s.startswith("* "):
            kind, body = "bullet", s[2:]
        else:
            kind, body = ("para" if seen_section else "header"), s
        blocks.append(Block(kind, _runs(body), i, s))
    return blocks


def resume_name(md: str) -> str:
    """The candidate's name as the resume states it (the first "# " line)."""
    for b in parse_md(md):
        if b.kind == "name":
            return b.text.strip()
    return ""


# ── Font metrics (fpdf2's own width rounding, so wraps match the PDF) ───────

_METRICS: dict[str, dict[int, int]] = {}
_METRICS_DEFAULT: dict[str, int] = {}
_METRICS_LOCK = threading.Lock()


def _widths(style: str) -> dict[int, int]:
    """codepoint -> advance in 1/1000 em, rounded exactly as fpdf2 rounds
    (``round(1000/upem * advance + 0.001)``) - the same numbers the PDF's /W
    array carries, so a line we measure is the line a viewer draws."""
    table = _METRICS.get(style)
    if table is not None:
        return table
    with _METRICS_LOCK:
        table = _METRICS.get(style)
        if table is not None:
            return table
        from fontTools.ttLib import TTFont

        font = TTFont(str(FONT_DIR / _FONT_FILES[style]), lazy=True)
        try:
            scale = 1000 / font["head"].unitsPerEm
            hmtx = font["hmtx"].metrics
            built: dict[int, int] = {}
            for cp, glyph in font.getBestCmap().items():
                w = hmtx[glyph][0]
                built[cp] = round(scale * (0 if w == 65535 else w) + 0.001)
            _METRICS_DEFAULT[style] = round(scale * hmtx[".notdef"][0] + 0.001)
        finally:
            font.close()
        _METRICS[style] = built
        return built


_SAFE_CACHE: dict[str, str] = {}
_PUNCT_FALLBACK = {
    "\t": " ",
    "\u2192": "->", "\u2190": "<-", "\u2194": "<->", "\u21d2": "=>",
    "\u2264": "<=", "\u2265": ">=", "\u2260": "!=", "\u2248": "~",
    "\u2713": "", "\u2714": "", "\u2717": "", "\u2605": "*", "\u2606": "*",
    "\u25cf": _BULLET, "\u25a0": _BULLET, "\u2023": _BULLET,
    "\u2043": "-", "\u2212": "-",
    # Carlito has no glyph for these; word processors and PDF copy-paste
    # produce them ("co\u2011founded", "5\u2032", "A\u2219B").
    "\u2010": "-", "\u2011": "-", "\u2032": "'", "\u2035": "'",
    "\u2219": "\u00b7", "\u2027": "\u00b7", "\u2236": ":",
    # Math symbols a LaTeX resume's PDF text carries ($\sim$40\% -> "\u223c40%",
    # \cdot and \ast separators, \langle/\rangle, long arrows).
    "\u223c": "~", "\u2243": "~", "\u2245": "~", "\u22c5": "\u00b7", "\u2217": "*",
    "\u2223": "|", "\u2218": "\u25e6", "\u2981": _BULLET, "\u22c4": "\u00b7",
    "\u21d4": "<=>", "\u27e8": "<", "\u27e9": ">", "\u27f5": "<-", "\u27f6": "->",
    "\u27f9": "=>", "\u2208": "in",
    # Separators and bullets from templates and CJK input methods.
    "\u25ba": _BULLET, "\u25b8": _BULLET, "\u276f": "\u203a", "\u203b": "*",
    "\u3002": ".", "\u3001": ",", "\u301c": "~", "\u300c": '"', "\u300d": '"',
    "\u3010": "[", "\u3011": "]", "\u300a": "\u00ab", "\u300b": "\u00bb",
    # Currency signs Carlito lacks: the amount must keep its currency.
    "\u20ba": "TRY ", "\u20bd": "RUB ", "\u20bf": "BTC ",
}
# A dash, quote, space or bracket the font lacks is still one; other
# punctuation and math symbols without a stand-in are decoration (dropped).
_CATEGORY_FALLBACK = {"Pd": "-", "Pi": "'", "Pf": "'", "Zs": " ", "Ps": "(", "Pe": ")",
                      "Pc": "_", "Po": "", "Sm": "", "Sk": "", "So": "",
                      "Cs": "", "Co": "", "Cn": "", "Me": ""}
# Invisible in Word, but a font that has a glyph for them would draw one.
_INVISIBLE = {ord(c): None for c in "\u00ad\u200b\u200c\u200d\u2060\ufeff"}
# Characters drawn as UNDRAWABLE for want of a glyph: letters, digits and
# currency signs, i.e. resume content (a name in CJK script). Recorded here,
# not inferred from the drawn text, because "?" is also a legitimate result
# (U+FF1F, the fullwidth question mark, folds to it).
_NO_GLYPH: set[str] = set()
UNDRAWABLE = "?"


def _safe_char(ch: str, cmap: dict[int, int]) -> str:
    if ord(ch) in cmap:
        return ch
    cached = _SAFE_CACHE.get(ch)
    if cached is not None:
        return cached
    out: Optional[str] = None
    if ch in _PUNCT_FALLBACK and all(ord(c) in cmap for c in _PUNCT_FALLBACK[ch]):
        out = _PUNCT_FALLBACK[ch]
    elif unicodedata.category(ch) in ("Cc", "Cf", "Zl", "Zp", "Mn"):
        out = " " if ch in "\n\r\v\f\u2028\u2029" else ""
    if out is None:
        nfkc = unicodedata.normalize("NFKC", ch)
        if nfkc != ch and nfkc and all(ord(c) in cmap for c in nfkc):
            out = nfkc
    if out is None:
        folded = unicodedata.normalize("NFKD", ch).encode("ascii", "ignore").decode()
        if folded:
            out = folded
    if out is None:
        # A pictograph (emoji, dingbat), a math sign or a stray mark carries
        # no resume content; a dash, quote, space or bracket keeps its role.
        out = _CATEGORY_FALLBACK.get(unicodedata.category(ch))
    if out is None:
        # A letter, digit or currency sign (e.g. a CJK name) is content this
        # font cannot draw.
        out = UNDRAWABLE
        _NO_GLYPH.add(ch)
        log.debug("resume pdf: no glyph for U+%04X", ord(ch))
    _SAFE_CACHE[ch] = out
    return out


def undrawable_chars(text: str) -> list[str]:
    """Distinct characters of ``text`` the PDF would print as "?": letters,
    digits or currency signs the bundled font has no glyph or stand-in for
    (a name in CJK script). Symbols and punctuation never count - they are
    drawn as a stand-in or dropped."""
    cmap = _widths("")
    text = unicodedata.normalize("NFC", text or "").translate(_INVISIBLE)
    out: list[str] = []
    for c in dict.fromkeys(text):
        if ord(c) in cmap:
            continue
        _safe_char(c, cmap)
        if c in _NO_GLYPH:
            out.append(c)
    return out


def _pdf_text(text: str) -> str:
    """Text the bundled font can draw. Carlito covers Latin (accents, smart
    quotes, bullets, dashes), Greek and Cyrillic; anything else degrades to
    its closest drawable form instead of an empty box or an exception."""
    cmap = _widths("")
    text = unicodedata.normalize("NFC", text).translate(_INVISIBLE)
    if all(ord(c) in cmap for c in text):
        return text
    return "".join(_safe_char(c, cmap) for c in text)


def text_width(text: str, style: str, size: float) -> float:
    """Advance width in points of ``text`` in Carlito ``style`` at ``size``."""
    table = _widths(style)
    default = _METRICS_DEFAULT.get(style, 0)
    return sum(table.get(ord(c), default) for c in text) * size * 0.001


# ── Layout ───────────────────────────────────────────────────────────────────

_HEADING_KINDS = ("name", "section", "subhead")


@dataclass
class _Laid:
    block: Block
    size: float
    lh: float
    before: float
    after: float
    color: tuple[int, int, int]
    x0: float                 # left edge of the text, relative to the margin
    bullet: bool
    rule: bool
    lines: list[list[tuple[float, str, str]]] = field(default_factory=list)

    @property
    def height(self) -> float:
        return self.lh * len(self.lines) + (_RULE_PAD_PT if self.rule else 0.0)


def _style_of(kind: str, tier: Tier):
    """(size, before, after, color, bullet, rule) - the Word styles' values."""
    if kind == "name":
        return tier.h1_pt, 0.0, tier.h1_after_pt, _DARK, False, False
    if kind == "section":
        return tier.h2_pt, tier.h2_before_pt, tier.h2_after_pt, _DARK, False, True
    if kind == "subhead":
        return tier.h3_pt, tier.h3_before_pt, tier.h3_after_pt, _DARK, False, False
    if kind == "bullet":
        return tier.body_pt, 0.0, tier.bullet_after_pt, _BODY, True, False
    return tier.body_pt, 0.0, tier.para_after_pt, _BODY, False, False


def _wrap(chars: list[tuple[str, str]], size: float, avail: float) -> list[list[tuple[float, str, str]]]:
    """Greedy word wrap over (char, style) pairs, the way Word breaks lines:
    at spaces (dropped at the break) and after a hyphen inside a word; a word
    wider than the line is split by characters. Returns lines of
    (x offset, text, style) segments."""
    tables = {s: _widths(s) for s in {st for _, st in chars}}
    k = size * 0.001

    def w(seq) -> float:
        return sum(tables[st].get(ord(c), _METRICS_DEFAULT.get(st, 0)) for c, st in seq) * k

    # Split into (spaces, word) chunks; a hyphen between two alphanumerics
    # ends a chunk with no space after it (Word's break-after-hyphen).
    chunks: list[tuple[list, list]] = []
    i, n = 0, len(chars)
    while i < n:
        j = i
        while j < n and chars[j][0] == " ":
            j += 1
        m = j
        while m < n and chars[m][0] != " ":
            m += 1
            if (chars[m - 1][0] == "-" and m < n and chars[m][0].isalnum()
                    and m - 2 >= j and chars[m - 2][0].isalnum()):
                break
        chunks.append((chars[i:j], chars[j:m]))
        i = m

    lines: list[list[tuple[str, str]]] = []
    cur: list[tuple[str, str]] = []
    cur_w = 0.0
    for spaces, word in chunks:
        if not word:
            continue  # trailing spaces never take width
        sw, ww = w(spaces), w(word)
        if cur and cur_w + sw + ww <= avail + _EPS:
            cur.extend(spaces)
            cur.extend(word)
            cur_w += sw + ww
            continue
        if cur:
            lines.append(cur)
            cur, cur_w = [], 0.0
        if ww <= avail + _EPS:
            cur, cur_w = list(word), ww
            continue
        for pair in word:  # longer than a whole line (a URL): break anywhere
            cw = w([pair])
            if cur and cur_w + cw > avail + _EPS:
                lines.append(cur)
                cur, cur_w = [], 0.0
            cur.append(pair)
            cur_w += cw
    if cur or not lines:
        lines.append(cur)

    out: list[list[tuple[float, str, str]]] = []
    for line in lines:
        segs: list[tuple[float, str, str]] = []
        x = 0.0
        buf, buf_style, buf_x = "", None, 0.0
        for c, st in line:
            if st != buf_style:
                if buf:
                    segs.append((buf_x, buf, buf_style))
                buf, buf_style, buf_x = "", st, x
            buf += c
            x += tables[st].get(ord(c), _METRICS_DEFAULT.get(st, 0)) * k
        if buf:
            segs.append((buf_x, buf, buf_style))
        out.append(segs)
    return out


def _lay(block: Block, tier: Tier) -> _Laid:
    size, before, after, color, bullet, rule = _style_of(block.kind, tier)
    heading = block.kind in _HEADING_KINDS
    chars: list[tuple[str, str]] = []
    for r in block.runs:
        st = "B" if (heading or r.bold) else ("I" if r.italic else "")
        chars.extend((c, st) for c in _pdf_text(r.text))
    x0 = tier.bullet_indent_pt if bullet else 0.0
    avail = PAGE_W_PT - 2 * tier.margin_pt - x0
    laid = _Laid(block, size, size * LINE_FACTOR * tier.line_spacing, before, after,
                 color, x0, bullet, rule)
    laid.lines = _wrap(chars, size, avail)
    return laid


def _gap(prev: Optional[_Laid], cur: _Laid) -> float:
    """Space between two paragraphs, as Word computes it: space after +
    space before, except between two List Bullet paragraphs, whose style
    carries contextualSpacing (no space between same-style paragraphs)."""
    if prev is None:
        return cur.before
    if prev.bullet and cur.bullet:
        return 0.0
    return prev.after + cur.before


@dataclass
class _Placed:
    laid: _Laid
    line: int          # index into laid.lines; -1 = the section rule
    y: float           # top of the line box (or the rule's y)


def _paginate(laid: list[_Laid], tier: Tier, reserve: float = 0.0) -> list[list[_Placed]]:
    """Place lines on Letter pages. A line that would cross the bottom margin
    (raised by ``reserve`` points) starts a new page; a heading is kept with
    the first line after it."""
    top = tier.margin_pt
    bottom = PAGE_H_PT - tier.margin_pt - reserve
    pages: list[list[_Placed]] = [[]]
    y = top
    prev: Optional[_Laid] = None
    for idx, lb in enumerate(laid):
        y += _gap(prev, lb)
        if lb.block.kind in _HEADING_KINDS and idx + 1 < len(laid) and y > top + _EPS:
            nxt = laid[idx + 1]
            need = lb.height + _gap(lb, nxt) + nxt.lh
            if y + need > bottom + _EPS:
                pages.append([])
                y = top
        for li in range(len(lb.lines)):
            if y + lb.lh > bottom + _EPS and y > top + _EPS:
                pages.append([])
                y = top
            pages[-1].append(_Placed(lb, li, y))
            y += lb.lh
        if lb.rule:
            pages[-1].append(_Placed(lb, -1, y + _RULE_GAP_PT + _RULE_W_PT / 2))
            y += _RULE_PAD_PT
        prev = lb
    return pages


class _LayoutCache:
    """Wrapped lines per (block, tier) so trims re-paginate without re-wrapping."""

    def __init__(self) -> None:
        self._d: dict[tuple[int, str], _Laid] = {}

    def lay(self, blocks: list[Block], tier: Tier) -> list[_Laid]:
        out = []
        for b in blocks:
            key = (b.line_no, tier.name)
            laid = self._d.get(key)
            if laid is None:
                laid = self._d[key] = _lay(b, tier)
            out.append(laid)
        return out


def layout_pages(md: str, tier: Union[Tier, int] = 0) -> int:
    """How many Letter pages ``md`` takes at ``tier`` (no PDF produced)."""
    t = _tier(tier)
    return len(_paginate([_lay(b, t) for b in parse_md(md)], t))


def word_reserve_pt(tier: Union[Tier, int]) -> float:
    """Spare space a fitting layout must leave at the bottom of the page: one
    body line at ``tier``. Word wraps with its own engine (kerning, its own
    justification of a line that is a hair too long); without this margin a
    PDF that fills its page exactly can become a two-page .docx."""
    t = _tier(tier)
    return t.body_pt * LINE_FACTOR * t.line_spacing


# ── PDF ──────────────────────────────────────────────────────────────────────

def _subset_tag(seed: bytes, font_name: bytes) -> bytes:
    for salt in range(64):
        digest = hashlib.sha256(seed + b"\0" + font_name + bytes([salt])).digest()
        tag = bytes(65 + (x % 26) for x in digest[:6])
        if not find_generator_markers(tag):  # six random capitals can spell "GPT"
            return tag
    return b"XQZKVJ"  # unreachable in practice


_SUBSET_RE = re.compile(rb"/MPDFAA\+([A-Za-z0-9\-]+)")


def _retag_subsets(pdf: bytes) -> bytes:
    """fpdf2 prefixes every embedded subset with the constant tag ``MPDFAA+``
    - a signature of the library. A subset tag is just six capitals (ISO
    32000 9.6.4), so each font gets one derived from the document's own
    content: same length (the xref offsets stay valid), no constant."""
    seed = hashlib.sha256(pdf).digest()
    return _SUBSET_RE.sub(lambda m: b"/" + _subset_tag(seed, m.group(1)) + b"+" + m.group(1), pdf)


def outside_streams(pdf: bytes) -> bytes:
    """The PDF minus its (binary) stream payloads: object dictionaries, the
    Info dict, the trailer - where a generator would leave its name. (A
    compressed payload is noise; three random bytes in it can read "GPT".)"""
    return re.sub(rb">>\s*stream\r?\n.*?endstream", b">> stream endstream", pdf, flags=re.S)


def find_generator_markers(data: bytes) -> list[str]:
    """Generator/vendor markers present in ``data`` (case-insensitive)."""
    low = data.lower()
    return [m for m in GENERATOR_MARKERS if m.encode() in low]


def _rewrite_pdf_metadata(pdf: bytes, author: str, title: str) -> bytes:
    """Last-resort metadata rewrite (an fpdf2 that ignores an empty producer):
    drop the Info dict and any XMP packet, write only author/title/date."""
    from pypdf import PdfReader, PdfWriter
    from pypdf.generic import NameObject

    writer = PdfWriter(clone_from=PdfReader(io.BytesIO(pdf)))
    writer.metadata = None
    root = getattr(writer, "root_object", None) or writer._root_object
    if NameObject("/Metadata") in root:
        del root[NameObject("/Metadata")]
    meta = {"/CreationDate": datetime.now(timezone.utc).strftime("D:%Y%m%d%H%M%SZ")}
    if author:
        meta["/Author"] = author
    if title:
        meta["/Title"] = title
    writer.add_metadata(meta)
    out = io.BytesIO()
    writer.write(out)
    return out.getvalue()


def _draw(pages: list[list[_Placed]], tier: Tier, *, author: str, title: str) -> bytes:
    from fpdf import FPDF

    pdf = FPDF(unit="pt", format="letter")
    pdf.set_auto_page_break(False)
    pdf.set_margins(tier.margin_pt, tier.margin_pt, tier.margin_pt)
    for style, fname in _FONT_FILES.items():
        pdf.add_font(_FONT_FAMILY, style, str(FONT_DIR / fname))
    # Metadata: the candidate is the author; nothing names the software.
    pdf.set_creator("")
    pdf.set_producer("")
    if author:
        pdf.set_author(author)
    if title:
        pdf.set_title(title)
    pdf.set_creation_date(datetime.now(timezone.utc))

    left = tier.margin_pt
    for page in pages:
        pdf.add_page()
        for placed in page:
            lb = placed.laid
            if placed.line < 0:
                pdf.set_draw_color(*_RULE)
                pdf.set_line_width(_RULE_W_PT)
                pdf.line(left, placed.y, PAGE_W_PT - tier.margin_pt, placed.y)
                continue
            # Extra leading of a >1.0 multiple sits above the text, as in Word.
            baseline = placed.y + lb.lh - _WIN_DESCENT * lb.size
            pdf.set_text_color(*lb.color)
            if lb.bullet and placed.line == 0:
                pdf.set_font(_FONT_FAMILY, "", lb.size)
                pdf.text(left, baseline, _BULLET)
            for dx, seg, style in lb.lines[placed.line]:
                pdf.set_font(_FONT_FAMILY, style, lb.size)
                pdf.text(left + lb.x0 + dx, baseline, seg)
    data = _retag_subsets(bytes(pdf.output()))
    # A candidate may be NAMED Claude; only flag what the document's own
    # author/title do not explain.
    own = f"{author} {title}".lower()
    if [m for m in find_generator_markers(outside_streams(data)) if m not in own]:
        data = _rewrite_pdf_metadata(data, author, title)
    return data


def render_pdf(md: str, tier: Union[Tier, int] = 0, *, author: str = "", title: str = "") -> bytes:
    """Render the markdown resume to PDF bytes at ``tier``.

    Letter, single column, real (selectable, ATS-parseable) text in the
    bundled Carlito font; no images, no tables. Metadata: Author = ``author``,
    Title = ``title``, a creation date, nothing else.
    """
    t = _tier(tier)
    pages = _paginate([_lay(b, t) for b in parse_md(md)], t)
    return _draw(pages, t, author=author, title=title)


def page_count(pdf_bytes: bytes) -> int:
    """Pages in a PDF, read back with pypdf (not from our own layout)."""
    from pypdf import PdfReader

    return len(PdfReader(io.BytesIO(pdf_bytes)).pages)


# ── One page: tiers, then deterministic bullet trims ────────────────────────

_TRIM_SECTION_RE = re.compile(
    r"\b(experiences?|employment|work|projects?|leadership|activities|career|history|"
    r"internships?|research|volunteer\w*|positions?|appointments?|engagements?)\b", re.I)
_PROTECTED_SECTION_RE = re.compile(
    r"(education|skill|summary|profile|objective|authori[sz]ation|certification|"
    r"qualification|contact|award|honou?r|publication|language)", re.I)

_STOPWORDS = frozenset("""
a about above across after again against all also am an and any are as at be
because been before being below between both but by can could did do does doing
down during each etc few for from further had has have having he her here hers
him his how i if in into is it its itself just me more most must my no nor not
now of off on once only or other our ours out over own per same she should so
some such than that the their theirs them then there these they this those
through to too under until up upon very via was we were what when where which
while who whom why will with within without would you your yours
ability able years year experience experienced work working team teams strong
including include includes role roles responsibilities requirements required
preferred qualifications plus nice bonus using use used new well join help
looking candidate candidates position company opportunity us across based
""".split())

_TOKEN_RE = re.compile(r"[a-z0-9][a-z0-9+#]*(?:[.\-/][a-z0-9+#]+)*")
_NUMERIC_RE = re.compile(r"[\d+.,%/\-]+")


def _terms(text: str) -> set[str]:
    """Lowercase words + adjacent-word bigrams, minus stopwords and numbers."""
    toks = [t for t in _TOKEN_RE.findall((text or "").lower())]
    keep = [t if (t not in _STOPWORDS and not _NUMERIC_RE.fullmatch(t)
                  and (len(t) > 1 or t in ("c", "r"))) else None for t in toks]
    terms = {t for t in keep if t}
    for a, b in zip(keep, keep[1:]):
        if a and b:
            terms.add(f"{a} {b}")
    return terms


def _is_trim_section(heading: str) -> bool:
    return bool(_TRIM_SECTION_RE.search(heading)) and not _PROTECTED_SECTION_RE.search(heading)


_DATE = (r"(?:(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\.?,?\s*|\d{1,2}/)?"
         r"(?:19|20)\d{2}")
_DATE_RANGE = (rf"{_DATE}\s*(?:-|\u2013|\u2014|to|until)\s*"
               rf"(?:{_DATE}|present|current|now|today|date)")
_DATE_RANGE_RE = re.compile(_DATE_RANGE, re.I)
_ENDS_WITH_DATE_RANGE_RE = re.compile(rf"{_DATE_RANGE}\)?\s*$", re.I)


def _is_role_line(b: Block) -> bool:
    """A role header written as a bullet: "- **Engineer** | Acme | 2020 - 2024",
    "- **Engineer, Acme**", "- Engineer, Acme, Jan 2020 - Present",
    "- **Engineer**, Acme, 2020 - 2024, Remote". Never trimmed, and it starts
    a new role like any other non-bullet line. Generous on purpose: an
    achievement bullet read as a header only stays on the page, while a
    header read as a bullet could be removed."""
    if b.kind != "bullet":
        return False
    body = b.raw[2:].strip()
    if body.startswith("**") and "|" in body:
        return True
    if b.runs and all(r.bold for r in b.runs if r.text.strip()):
        return True
    text = b.text
    if not _DATE_RANGE_RE.search(text):
        return False
    return bool(_ENDS_WITH_DATE_RANGE_RE.search(text) or "|" in text
                or body.startswith("**")
                or (text.count(",") >= 2 and len(text) <= 100))


def _roles(blocks: list[Block]) -> list[list[Block]]:
    """Runs of trimmable bullets, document order, trimmable sections only.

    Any line in such a section that is not a plain bullet - a "### "
    subhead, a "**Engineer** | Acme | 2023 - 2025" line, a plain "Engineer,
    Acme, 2023 - 2025" line, a bulleted role header - ends the current run;
    consecutive such lines (company line + title line) start one run.
    Grouping by run rather than by recognising role lines means a role
    header in an unexpected shape can never merge two roles into one, where
    trimming could empty one of them.
    """
    roles: list[list[Block]] = []
    in_trim = False
    cur: Optional[list[Block]] = None
    for b in blocks:
        if b.kind in ("section", "name"):
            in_trim = b.kind == "section" and _is_trim_section(b.text)
            cur = None
            continue
        if not in_trim:
            continue
        if b.kind != "bullet" or _is_role_line(b):
            if cur is None or cur:
                cur = []
                roles.append(cur)
            continue
        if cur is None:
            cur = []
            roles.append(cur)
        cur.append(b)
    return [r for r in roles if r]


def _trim_order(blocks: list[Block], jd_text: str) -> list[Block]:
    """Removable bullets, first to go first: fewest job-description terms,
    then the later (older) role, then the longer bullet. Each run keeps its
    most relevant bullet (ties: the first, which writers lead with)."""
    jd = _terms(jd_text)
    scored: list[tuple[int, int, int, int, Block]] = []
    for gi, role in enumerate(_roles(blocks)):
        if len(role) < 2:
            continue
        rel = {id(b): len(_terms(b.text) & jd) for b in role}
        keep = max(role, key=lambda b: (rel[id(b)], -b.line_no))
        for b in role:
            if b is not keep:
                scored.append((rel[id(b)], -gi, -len(b.text), -b.line_no, b))
    scored.sort(key=lambda s: s[:4])
    return [s[4] for s in scored]


def trim_candidates(md: str, jd_text: str = "") -> list[str]:
    """Bullet texts in the order ``fit_one_page`` would remove them."""
    return [b.text for b in _trim_order(parse_md(md), jd_text)]


@dataclass
class FitResult:
    md: str                    # the (possibly trimmed) markdown - write the DOCX from this
    pdf_bytes: bytes
    tier_index: int
    pages: int                 # read back from the PDF bytes with pypdf
    trimmed: list[str] = field(default_factory=list)  # removed bullet texts, in order
    # characters the PDF prints as "?" (no glyph in the bundled font); when
    # non-empty the PDF misstates the resume and must not be delivered
    undrawable: list[str] = field(default_factory=list)

    @property
    def tier(self) -> Tier:
        return TIERS[self.tier_index]

    @property
    def one_page(self) -> bool:
        return self.pages == 1


def _drop_lines(md: str, line_nos: set[int]) -> str:
    if not line_nos:
        return md
    lines = md.splitlines(keepends=True)
    return "".join(ln for i, ln in enumerate(lines) if i not in line_nos)


def fit_one_page(md: str, *, jd_text: str = "", author: str = "", title: str = "",
                 max_renders: int = 8) -> FitResult:
    """The densest-needed layout that puts the resume on ONE page.

    1. Tiers T0..T3 in order; the first that paginates to one page with
       ``word_reserve_pt`` to spare wins.
    2. Still too long at T3: remove bullets one at a time in
       ``trim_candidates`` order (fewest job-description terms first, then
       the older role, then the longer bullet; each run of bullets keeps one)
       until it fits or nothing removable is left. Removal only - no line is
       added or reworded.

    Every attempt is laid out by the same pagination ``render_pdf`` draws
    with, so trying a tier or a trim costs arithmetic, not a PDF.
    ``max_renders`` bounds the PDFs actually produced: one normally; more only
    if pypdf disagreed with the layout (it should not), in which case trimming
    continues against real renders.
    """
    blocks = parse_md(md)
    cache = _LayoutCache()

    def fits(kept: list[Block], t: Tier) -> bool:
        return len(_paginate(cache.lay(kept, t), t, word_reserve_pt(t))) == 1

    tier_index = len(TIERS) - 1
    for i, t in enumerate(TIERS):
        if fits(blocks, t):
            tier_index = i
            break
    tier = TIERS[tier_index]

    removed: list[Block] = []
    kept = list(blocks)
    order = _trim_order(blocks, jd_text)
    if not fits(kept, tier):
        for b in order:
            removed.append(b)
            kept = [k for k in kept if k is not b]
            if fits(kept, tier):
                break
        else:
            # Nothing removable is left: the sections that hold the bullets
            # are not ones fitting may touch (headings outside
            # _TRIM_SECTION_RE), or every role is down to one bullet.
            log.warning("resume fit: no removable bullet left at %s (%d removable of %d "
                        "blocks) - the layout may run past one page",
                        tier.name, len(order), len(blocks))

    renders = 0
    while True:
        out_md = _drop_lines(md, {b.line_no for b in removed})
        pdf = _draw(_paginate(cache.lay(kept, tier), tier), tier, author=author, title=title)
        renders += 1
        pages = page_count(pdf)
        remaining = [b for b in order if b not in removed]
        if pages == 1 or not remaining or renders >= max(1, max_renders):
            break
        log.warning("resume fit: layout said 1 page, pypdf read %d - trimming further", pages)
        removed.append(remaining[0])
        kept = [k for k in kept if k is not remaining[0]]

    if removed:
        log.info("resume fit: %s with %d bullet(s) trimmed -> %d page(s)",
                 tier.name, len(removed), pages)
    if pages > 1:
        log.warning("resume fit: %d pages at %s after %d trim(s)", pages, tier.name, len(removed))
    return FitResult(md=out_md, pdf_bytes=pdf, tier_index=tier_index, pages=pages,
                     trimmed=[b.text for b in removed],
                     undrawable=undrawable_chars("\n".join(b.text for b in kept)))


# ── Word ─────────────────────────────────────────────────────────────────────

_XML_BAD_RE = re.compile("[\x00-\x08\x0b\x0c\x0e-\x1f\ufffe\uffff]")
_DOCX_STYLE = {"name": "Heading 1", "section": "Heading 2", "subhead": "Heading 3",
               "bullet": "List Bullet"}


def _calibri(rpr_parent) -> None:
    """Point a style's (or docDefaults') rFonts at Calibri for real: an
    ``asciiTheme`` attribute outranks ``ascii``, and the template's theme
    resolves the minor font to Cambria."""
    from docx.oxml.ns import qn

    rpr = rpr_parent.get_or_add_rPr() if hasattr(rpr_parent, "get_or_add_rPr") else rpr_parent
    rfonts = rpr.find(qn("w:rFonts"))
    if rfonts is None:
        rfonts = rpr.makeelement(qn("w:rFonts"), {})
        rpr.insert(0, rfonts)
    for a in ("w:asciiTheme", "w:hAnsiTheme", "w:cstheme"):
        rfonts.attrib.pop(qn(a), None)
    for a in ("w:ascii", "w:hAnsi", "w:cs"):
        rfonts.set(qn(a), "Calibri")


def _apply_tier_styles(doc, tier: Tier) -> None:
    """``tailor._set_ats_safe_styles`` with the tier's numbers (T0 = identical
    sizes/margins/spacing), plus: explicit line spacing, Calibri that is not
    overridden by the theme, and the thin rule under section headings that
    the PDF draws."""
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from docx.shared import Inches, Pt, RGBColor

    for sec in doc.sections:
        sec.page_width = Inches(8.5)
        sec.page_height = Inches(11)
        sec.top_margin = sec.bottom_margin = Inches(tier.margin_in)
        sec.left_margin = sec.right_margin = Inches(tier.margin_in)

    defaults = doc.styles.element.find(qn("w:docDefaults"))
    if defaults is not None:
        rpr = defaults.find(qn("w:rPrDefault") + "/" + qn("w:rPr"))
        if rpr is not None:
            _calibri(rpr)

    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(tier.body_pt)
    pf = normal.paragraph_format
    pf.space_before = Pt(0)
    pf.space_after = Pt(tier.para_after_pt)
    pf.line_spacing = tier.line_spacing  # a float = Word "multiple" (lineRule auto)
    _calibri(normal.element)

    def heading(name: str, size: float, before: float, after: float):
        st = doc.styles[name]
        st.font.name = "Calibri"
        st.font.size = Pt(size)
        st.font.bold = True
        st.font.color.rgb = RGBColor(*_DARK)
        st.paragraph_format.space_before = Pt(before)
        st.paragraph_format.space_after = Pt(after)
        _calibri(st.element)
        return st

    heading("Heading 1", tier.h1_pt, 0.0, tier.h1_after_pt)
    h2 = heading("Heading 2", tier.h2_pt, tier.h2_before_pt, tier.h2_after_pt)
    heading("Heading 3", tier.h3_pt, tier.h3_before_pt, tier.h3_after_pt)

    ppr = h2.element.get_or_add_pPr()
    if ppr.find(qn("w:pBdr")) is None:
        pbdr = OxmlElement("w:pBdr")
        bottom = OxmlElement("w:bottom")
        bottom.set(qn("w:val"), "single")
        bottom.set(qn("w:sz"), str(int(_RULE_W_PT * 8)))
        bottom.set(qn("w:space"), str(int(_RULE_GAP_PT)))
        bottom.set(qn("w:color"), "%02X%02X%02X" % _RULE)
        pbdr.append(bottom)
        ppr.insert_element_before(
            pbdr, "w:shd", "w:tabs", "w:suppressAutoHyphens", "w:kinsoku", "w:wordWrap",
            "w:overflowPunct", "w:topLinePunct", "w:autoSpaceDE", "w:autoSpaceDN",
            "w:bidi", "w:adjustRightInd", "w:snapToGrid", "w:spacing", "w:ind",
            "w:contextualSpacing", "w:mirrorIndents", "w:suppressOverlap", "w:jc",
            "w:textDirection", "w:textAlignment", "w:textboxTightWrap",
            "w:outlineLvl", "w:divId", "w:cnfStyle", "w:rPr", "w:sectPr", "w:pPrChange")

    lb = doc.styles["List Bullet"]
    lb.font.name = "Calibri"
    lb.font.size = Pt(tier.body_pt)
    lb.paragraph_format.space_after = Pt(tier.bullet_after_pt)
    lb.paragraph_format.left_indent = Inches(tier.bullet_indent_in)
    lb.paragraph_format.first_line_indent = Inches(-tier.bullet_indent_in)
    _calibri(lb.element)


def _docx_text(s: str) -> str:
    return _XML_BAD_RE.sub("", s.replace("\t", " "))


def write_docx(md: str, path: Union[str, Path], tier: Union[Tier, int] = 0, *,
               author: str = "", title: str = "") -> Path:
    """Write the markdown resume as an ATS-safe .docx at ``tier`` - the same
    paragraphs, sizes and margins the PDF uses - then scrub its metadata.

    Single column; standard Heading 1/2/3, List Bullet and Normal styles; no
    tables, text boxes, headers or footers.
    """
    from docx import Document

    t = _tier(tier)
    doc = Document()
    _apply_tier_styles(doc, t)
    for b in parse_md(md):
        p = doc.add_paragraph(style=_DOCX_STYLE.get(b.kind, "Normal"))
        for r in b.runs:
            run = p.add_run(_docx_text(r.text))
            if r.bold:
                run.bold = True
            if r.italic:
                run.italic = True
    buf = io.BytesIO()
    doc.save(buf)
    out = Path(path)
    _atomic_write(out, _scrub_docx_bytes(buf.getvalue(), author=author, title=title))
    return out


def _atomic_write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=".tmp-", suffix=path.suffix)
    try:
        with os.fdopen(fd, "wb") as fh:
            fh.write(data)
        os.chmod(tmp, 0o644)  # mkstemp creates 0600; match a plain write
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


_CORE_XML = (
    "<?xml version='1.0' encoding='UTF-8' standalone='yes'?>\n"
    '<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties"'
    ' xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/"'
    ' xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
    "{title}{creator}{last}"
    "<cp:revision>1</cp:revision>"
    '<dcterms:created xsi:type="dcterms:W3CDTF">{now}</dcterms:created>'
    '<dcterms:modified xsi:type="dcterms:W3CDTF">{now}</dcterms:modified>'
    "</cp:coreProperties>"
)

_APP_XML = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
    '<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"'
    ' xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">'
    "<TotalTime>0</TotalTime><DocSecurity>0</DocSecurity><ScaleCrop>false</ScaleCrop>"
    "<LinksUpToDate>false</LinksUpToDate><SharedDoc>false</SharedDoc>"
    "<HyperlinksChanged>false</HyperlinksChanged></Properties>"
)

_THUMBNAIL_REL = "/relationships/metadata/thumbnail"
_CUSTOMXML_REL = "/relationships/customXml"


# OPC package parts (relationships, content types) are flat lists of empty
# elements; removing one is a text edit, no XML parser (or lxml import) needed.
_REL_RE = re.compile(rb"<Relationship\b[^>]*?(?:/>|>\s*</Relationship>)")
_OVERRIDE_RE = re.compile(rb"<Override\b[^>]*?(?:/>|>\s*</Override>)")


def _attr(el: bytes, name: bytes) -> str:
    m = re.search(rb"\b" + name + rb"\s*=\s*([\"'])(.*?)\1", el)
    return m.group(2).decode("utf-8", "replace") if m else ""


def _drop_rels(xml: bytes, type_suffix: str) -> tuple[bytes, list[str]]:
    """Remove relationships whose Type ends with ``type_suffix``; return the
    new XML and the removed targets."""
    targets: list[str] = []

    def repl(m: re.Match) -> bytes:
        if _attr(m.group(0), b"Type").endswith(type_suffix):
            targets.append(_attr(m.group(0), b"Target"))
            return b""
        return m.group(0)

    out = _REL_RE.sub(repl, xml)
    return (out, targets) if targets else (xml, [])


def _drop_overrides(xml: bytes, part_names: tuple[str, ...]) -> bytes:
    def repl(m: re.Match) -> bytes:
        return b"" if _attr(m.group(0), b"PartName").lstrip("/") in part_names else m.group(0)

    return _OVERRIDE_RE.sub(repl, xml)


_RSID_DECL_RE = re.compile(rb"(<w:rsid(?:Root)?\s+w:val=\")([0-9A-Fa-f]{8})(\")")
_RSID_ATTR_RE = re.compile(rb"(w:rsid[A-Za-z]*=\")([0-9A-Fa-f]{8})(\")")
_DOCID_RE = re.compile(rb"(<w1[45]:docId\s+w1[45]:val=\")([0-9A-Fa-f]{8})(\")")


def _fresh_revision_ids(payload: dict[str, bytes]) -> None:
    """Replace the template's revision-session ids and document id with
    random ones, consistently across every word/*.xml part.

    python-docx copies its template's parts verbatim, so every file it writes
    carries the SAME ``w:rsidRoot``/``w:rsid`` list and ``w14:docId`` - a
    fingerprint shared by all of them. Every id in any part is remapped,
    including ones settings.xml never declares (the template's styles.xml
    carries one on its Header/Footer styles). Word's own ids are random
    24-bit values, written as 8 hex digits.
    """
    parts = [n for n in payload if n.startswith("word/") and n.endswith(".xml")]
    old = list(dict.fromkeys(
        m.group(2).upper()
        for name in parts
        for rx in (_RSID_DECL_RE, _RSID_ATTR_RE)
        for m in rx.finditer(payload[name])))
    fresh: dict[bytes, bytes] = {}
    for o in old:
        while True:
            new = ("00%06X" % int.from_bytes(os.urandom(3), "big")).encode()
            if new not in fresh.values() and new not in old:
                break
        fresh[o] = new

    def rsid(m: re.Match) -> bytes:
        return m.group(1) + fresh.get(m.group(2).upper(), m.group(2)) + m.group(3)

    def docid(m: re.Match) -> bytes:
        val = ("%08X" % (int.from_bytes(os.urandom(4), "big") & 0x7FFFFFFF)).encode()
        return m.group(1) + val + m.group(3)

    for name in parts:
        xml = payload[name]
        if fresh:
            xml = _RSID_ATTR_RE.sub(rsid, xml)
            xml = _RSID_DECL_RE.sub(rsid, xml)
        xml = _DOCID_RE.sub(docid, xml)
        payload[name] = xml


def _scrub_docx_bytes(data: bytes, *, author: str = "", title: str = "") -> bytes:
    """Rewrite a .docx so its package names the candidate, not the software.

    * docProps/core.xml: rewritten - creator/lastModifiedBy = ``author``,
      title, revision 1, created/modified = now; no subject, keywords,
      description ("generated by python-docx") or category.
    * docProps/app.xml: minimal - no Application ("Microsoft Macintosh
      Word"), AppVersion, Company, Template or the template's static counts.
    * the template's thumbnail (identical in every python-docx file) and its
      bibliography customXml part (a fixed GUID) are removed with their
      relationships and content-type overrides.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    a = _xml_escape(_docx_text(author or "").strip())
    t = _xml_escape(_docx_text(title or "").strip())
    core = _CORE_XML.format(
        title=f"<dc:title>{t}</dc:title>" if t else "",
        creator=f"<dc:creator>{a}</dc:creator>" if a else "",
        last=f"<cp:lastModifiedBy>{a}</cp:lastModifiedBy>" if a else "",
        now=now,
    ).encode("utf-8")

    src = zipfile.ZipFile(io.BytesIO(data))
    names = src.namelist()
    payload = {n: src.read(n) for n in names}
    src.close()

    dropped: set[str] = set()
    if "_rels/.rels" in payload:
        payload["_rels/.rels"], targets = _drop_rels(payload["_rels/.rels"], _THUMBNAIL_REL)
        dropped.update(x.lstrip("/") for x in targets)
    doc_rels = "word/_rels/document.xml.rels"
    if doc_rels in payload:
        payload[doc_rels], targets = _drop_rels(payload[doc_rels], _CUSTOMXML_REL)
        if targets:
            dropped.update(n for n in names if n.startswith("customXml/"))
    dropped &= set(names)
    if "[Content_Types].xml" in payload and dropped:
        payload["[Content_Types].xml"] = _drop_overrides(
            payload["[Content_Types].xml"], tuple(sorted(dropped)))
    if "docProps/core.xml" in payload:
        payload["docProps/core.xml"] = core
    if "docProps/app.xml" in payload:
        payload["docProps/app.xml"] = _APP_XML.encode("utf-8")
    _fresh_revision_ids(payload)

    stamp = datetime.now().timetuple()[:6]
    out = io.BytesIO()
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        for n in names:
            if n in dropped:
                continue
            info = zipfile.ZipInfo(n, date_time=stamp)
            info.compress_type = zipfile.ZIP_DEFLATED
            zf.writestr(info, payload[n])
    return out.getvalue()


def scrub_docx_metadata(path: Union[str, Path], *, author: str = "", title: str = "") -> Path:
    """Scrub generator traces from an existing .docx in place (see
    ``_scrub_docx_bytes``). Works on any python-docx output, including
    ``tailor._md_to_docx``'s."""
    p = Path(path)
    _atomic_write(p, _scrub_docx_bytes(p.read_bytes(), author=author, title=title))
    return p


# ── File names ───────────────────────────────────────────────────────────────

_CORP_SUFFIXES = frozenset({
    "inc", "incorporated", "llc", "llp", "ltd", "limited", "corp", "corporation",
    "gmbh", "plc", "co", "lp", "sa", "ag", "bv",
})


# Letters NFKD does not decompose to ASCII (they are letters of their own,
# not an ASCII letter plus an accent), spelled the way names conventionally
# transliterate them.
_TRANSLIT = str.maketrans({
    "Ł": "L", "ł": "l", "ß": "ss", "ẞ": "SS", "Ø": "O", "ø": "o", "Æ": "AE", "æ": "ae",
    "Œ": "OE", "œ": "oe", "Đ": "D", "đ": "d", "Ð": "D", "ð": "d", "Þ": "Th", "þ": "th",
    "ı": "i", "Ħ": "H", "ħ": "h", "Ŀ": "L", "ŀ": "l", "Ŧ": "T", "ŧ": "t", "ĸ": "k",
    "\u2019": "'", "\u02bc": "'", "\u2018": "'",
})
_APOSTROPHES_ETC_RE = re.compile(r"['`.&]")


def _ascii(s: str) -> str:
    s = (s or "").translate(_TRANSLIT)
    return unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode("ascii")


def _fold(s: str) -> str:
    """ASCII fold + drop apostrophes/periods/ampersands + non-alnum runs -> _."""
    s = _APOSTROPHES_ETC_RE.sub("", _ascii(s))
    return re.sub(r"[^A-Za-z0-9]+", "_", s).strip("_")


def _name_part(s: str) -> str:
    # Judged before transliteration: an all-caps "WEIß" keeps a lowercase ß
    # (the conventional caps spelling) that would otherwise become "ss".
    letters = [c for c in (s or "") if c.isalpha() and c != "ß"]
    plain = _ascii(s)
    if len(letters) >= 2 and all(c.isupper() for c in letters):
        # "PRIYA RAMANATHAN" as the resume heading writes it -> Priya;
        # capitalised per piece BEFORE the apostrophe goes: O'BRIEN -> OBrien
        plain = re.sub(r"[A-Za-z]+", lambda m: m.group(0).capitalize(), plain)
    return _fold(plain)[:40].strip("_")


def document_filename(first: str, last: str, company: str, kind: str = "Resume",
                      ext: str = "docx") -> str:
    """``First_Last_Resume.docx`` - the owner's naming rule; tailoring passes
    a blank ``company`` (the owner dropped it from the name, 2026-10-08).

    Accents fold to ASCII ("José" -> "Jose", "Łukasz" -> "Lukasz", "Weiß" ->
    "Weiss"), apostrophes/periods/& vanish ("O'BRIEN" -> "OBrien"), other
    punctuation and spaces become one underscore. A company, when given,
    loses trailing corporate suffixes (Inc, LLC, Ltd, Corp, GmbH, PLC, Co, LP,
    SA, AG, BV, ...) and is capped at 40 characters; a blank one drops its
    segment. Blank names fall back to "Candidate". ``kind`` is "Resume" or
    "Cover_Letter".
    """
    name = "_".join(p for p in (_name_part(first), _name_part(last)) if p) or "Candidate"

    toks = [t for t in _fold(company).split("_") if t]
    while len(toks) > 1 and toks[-1].lower() in _CORP_SUFFIXES:
        toks.pop()
    comp = "_".join(toks)[:40].strip("_")

    kind_part = _fold(kind) or "Resume"
    ext_part = re.sub(r"[^A-Za-z0-9]", "", ext or "").lower()
    stem = "_".join(p for p in (name, comp, kind_part) if p)
    return f"{stem}.{ext_part}" if ext_part else stem


__all__ = [
    "Block", "FitResult", "GENERATOR_MARKERS", "Run", "TIERS", "Tier",
    "document_filename", "find_generator_markers", "fit_one_page", "layout_pages",
    "outside_streams", "page_count", "parse_md", "render_pdf", "resume_name",
    "scrub_docx_metadata",
    "text_width", "trim_candidates", "undrawable_chars", "word_reserve_pt", "write_docx",
]
